# Tratamento de erros
 # Try e Except
'''try:
    valores = int(input('Digite algo: '))
    print(valores)
except ValueError:
    print('Digite algum número.')
finally:
    print('Rode o código novamente.')
'''

